version: '3.9'

services:

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-q", "-d", "devdb", "-U", "devuser" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: diegoalencar.jacober@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456

volumes:
  dev-db-data: